name: dev

on:
  push:
    branches:
      - release/prd  # プルリクのマージもPushになる

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
      - run: npm install
      - run: npm run build-prd
      
      - name: prd deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CONOHA_HOST }}
          username: ${{ secrets.CONOHA_USERNAME }}
          port: ${{ secrets.CONOHA_PORT }}
          fingerprint: ${{ secrets.CONOHA_FINGERPRINT }}
          source: "dist/*"
          target: "public_html/mirumi.me/apps/yourcat"
          rm: true
